# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 308419160bbb33e494fe7d66f9c96fa4bf198692a90f1a3d250dc893e3fdac7376574f179c69bee2f05aa0bfbb55332eda76e8f7e5045397596859c4e2b65a63

test:
  secret_key_base: e55d787fcaf7f43fafde984d9a9c87053b562e445b311b1a0fbb69fd3a1d17ab3e5b9e921246af6c5222b1182e08c10c68fd2e3c898bd5f82a79115d298b94be

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
